// <auto-generated />
using System;
using System.Collections.Generic;
using CatalogingSystem.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogingSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogingSystem.Core.Entities.AdministrativeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CatalogingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectionType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryForm")
                        .HasColumnType("text");

                    b.Property<string>("EntrySource")
                        .HasColumnType("text");

                    b.Property<long>("FileNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileNumber")
                        .IsUnique();

                    b.ToTable("AdministrativeData");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.ArchivoAdministrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("archivoDocumental")
                        .HasColumnType("text");

                    b.Property<string>("asunto")
                        .HasColumnType("text");

                    b.Property<string>("documentoOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("expedienteAnterior")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fechaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaInicial")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("historial")
                        .HasColumnType("text");

                    b.Property<string>("institucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<bool?>("peticionTransferencia")
                        .HasColumnType("boolean");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<string>("unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente")
                        .IsUnique();

                    b.ToTable("ArchivosAdministrativos");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ActionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<long?>("Expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("NewData")
                        .HasColumnType("text");

                    b.Property<string>("OldData")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Conservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AffectedArea")
                        .HasColumnType("text");

                    b.Property<string>("AnalysisTypes")
                        .HasColumnType("text");

                    b.Property<string>("Depth")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("Expediente")
                        .HasColumnType("bigint");

                    b.Property<long>("Inventory")
                        .HasColumnType("bigint");

                    b.Property<string>("Length")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Reports")
                        .HasColumnType("text");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<string>("SpecialConditions")
                        .HasColumnType("text");

                    b.Property<string>("TreatmentType")
                        .HasColumnType("text");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Expediente")
                        .IsUnique();

                    b.ToTable("Conservations");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Dating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Expediente")
                        .HasColumnType("bigint");

                    b.Property<long>("Inventory")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Expediente")
                        .IsUnique();

                    b.ToTable("Datings");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.DescriptionClassification.DescriptionClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("Expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Expediente")
                        .IsUnique();

                    b.ToTable("DescriptionClassifications");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.GraphicDocumentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("generalObservations")
                        .HasColumnType("text");

                    b.Property<string>("genericControlNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("imageUrls")
                        .HasColumnType("text[]");

                    b.Property<long>("inventory")
                        .HasColumnType("bigint");

                    b.Property<string>("specificControlNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("supportTypes")
                        .HasColumnType("text[]");

                    b.Property<string>("technicalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente")
                        .IsUnique();

                    b.ToTable("GraphicDocumentations");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Identification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("genericClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("inventory")
                        .HasColumnType("bigint");

                    b.Property<int>("numberOfObjects")
                        .HasColumnType("integer");

                    b.Property<string>("objectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente");

                    b.ToTable("Identifications");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.TemporalMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<long>("Expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("Insurer")
                        .HasColumnType("text");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Policy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Expediente");

                    b.ToTable("TemporalMovements");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.TenantCustomization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryButton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadOnly")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Researcher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryButton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedSteps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TenantCustomizations");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int?>("PermissionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.AdministrativeData", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.AdministrativeData", "FileNumber")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Cataloger", "Cataloger", b1 =>
                        {
                            b1.Property<Guid>("AdministrativeDataId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .HasColumnType("text");

                            b1.Property<string>("IdentityCard")
                                .HasColumnType("text");

                            b1.Property<string>("Institution")
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .HasColumnType("text");

                            b1.Property<string>("Observations")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .HasColumnType("text");

                            b1.Property<string>("References")
                                .HasColumnType("text");

                            b1.HasKey("AdministrativeDataId");

                            b1.ToTable("AdministrativeData");

                            b1.WithOwner()
                                .HasForeignKey("AdministrativeDataId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.CopiesReproductions", "CopiesReproductions", b1 =>
                        {
                            b1.Property<Guid>("AdministrativeDataId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Author")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Format")
                                .HasColumnType("text");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalDestination")
                                .HasColumnType("text");

                            b1.Property<string>("OriginalTitle")
                                .HasColumnType("text");

                            b1.HasKey("AdministrativeDataId");

                            b1.ToTable("AdministrativeData");

                            b1.WithOwner()
                                .HasForeignKey("AdministrativeDataId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Valuation", "Valuation", b1 =>
                        {
                            b1.Property<Guid>("AdministrativeDataId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Appraiser")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("AdministrativeDataId");

                            b1.ToTable("AdministrativeData");

                            b1.WithOwner()
                                .HasForeignKey("AdministrativeDataId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("Cataloger");

                    b.Navigation("CopiesReproductions");

                    b.Navigation("Valuation");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Conservation", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.Conservation", "Expediente")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchivoAdministrativo");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Dating", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.Dating", "Expediente")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.ApproximateDating", "ApproximateDating", b1 =>
                        {
                            b1.Property<Guid>("DatingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int?>("FromCentury")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<int?>("ToCentury")
                                .HasColumnType("integer");

                            b1.HasKey("DatingId");

                            b1.ToTable("Datings");

                            b1.WithOwner()
                                .HasForeignKey("DatingId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("DatingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.HasKey("DatingId");

                            b1.ToTable("Datings");

                            b1.WithOwner()
                                .HasForeignKey("DatingId");

                            b1.OwnsOne("CatalogingSystem.Core.Entities.DateDetail", "From", b2 =>
                                {
                                    b2.Property<Guid>("DateRangeDatingId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Approximate")
                                        .HasColumnType("text");

                                    b2.Property<long?>("BC")
                                        .HasColumnType("bigint");

                                    b2.Property<long?>("Day")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Exact")
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsPresent")
                                        .HasColumnType("boolean");

                                    b2.Property<long?>("Month")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Probable")
                                        .HasColumnType("text");

                                    b2.Property<long?>("Year")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DateRangeDatingId");

                                    b2.ToTable("Datings");

                                    b2.WithOwner()
                                        .HasForeignKey("DateRangeDatingId");
                                });

                            b1.OwnsOne("CatalogingSystem.Core.Entities.DateDetail", "To", b2 =>
                                {
                                    b2.Property<Guid>("DateRangeDatingId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Approximate")
                                        .HasColumnType("text");

                                    b2.Property<long?>("BC")
                                        .HasColumnType("bigint");

                                    b2.Property<long?>("Day")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Exact")
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsPresent")
                                        .HasColumnType("boolean");

                                    b2.Property<long?>("Month")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Probable")
                                        .HasColumnType("text");

                                    b2.Property<long?>("Year")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DateRangeDatingId");

                                    b2.ToTable("Datings");

                                    b2.WithOwner()
                                        .HasForeignKey("DateRangeDatingId");
                                });

                            b1.Navigation("From");

                            b1.Navigation("To");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DatingNotes", "Notes", b1 =>
                        {
                            b1.Property<Guid>("DatingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("FinalDateNotes")
                                .HasColumnType("text");

                            b1.Property<string>("InitialDateNotes")
                                .HasColumnType("text");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<string>("Observations")
                                .HasColumnType("text");

                            b1.Property<string>("TextualDate")
                                .HasColumnType("text");

                            b1.HasKey("DatingId");

                            b1.ToTable("Datings");

                            b1.WithOwner()
                                .HasForeignKey("DatingId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.SimpleDate", "SimpleDate", b1 =>
                        {
                            b1.Property<Guid>("DatingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Approximate")
                                .HasColumnType("text");

                            b1.Property<long?>("BC")
                                .HasColumnType("bigint");

                            b1.Property<long?>("Day")
                                .HasColumnType("bigint");

                            b1.Property<string>("Exact")
                                .HasColumnType("text");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<long?>("Month")
                                .HasColumnType("bigint");

                            b1.Property<string>("Probable")
                                .HasColumnType("text");

                            b1.Property<long?>("Year")
                                .HasColumnType("bigint");

                            b1.HasKey("DatingId");

                            b1.ToTable("Datings");

                            b1.WithOwner()
                                .HasForeignKey("DatingId");
                        });

                    b.Navigation("ApproximateDating");

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("DateRange");

                    b.Navigation("Notes");

                    b.Navigation("SimpleDate");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.DescriptionClassification.DescriptionClassification", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.DescriptionClassification.DescriptionClassification", "Expediente")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.Bibliography", "Bibliography", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Author")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Page")
                                .HasColumnType("text");

                            b1.Property<string>("RegistrationNumber")
                                .HasColumnType("text");

                            b1.Property<string>("SourceDocument")
                                .HasColumnType("text");

                            b1.Property<string>("TextualCitation")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.CollectionProvenance", "CollectionProvenance", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Canton")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .HasColumnType("text");

                            b1.Property<string>("SpecificPlace")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.CulturalContext", "CulturalContext", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("RelatedCulturalElements")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.Decoration", "Decoration", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("MotifOrIconIdentification")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.DescriptionDimensions", "DescriptionDimensions", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("BaseCircumference")
                                .HasColumnType("text");

                            b1.Property<string>("BodyCircumference")
                                .HasColumnType("text");

                            b1.Property<string>("Depth")
                                .HasColumnType("text");

                            b1.Property<string>("Length")
                                .HasColumnType("text");

                            b1.Property<string>("MouthCircumference")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("ObjectTypeSpecifications")
                                .HasColumnType("text");

                            b1.Property<string>("Thickness")
                                .HasColumnType("text");

                            b1.Property<string>("Width")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.Inscriptions", "Inscriptions", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Author")
                                .HasColumnType("text");

                            b1.Property<string>("CharacterType")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Language")
                                .HasColumnType("text");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Script")
                                .HasColumnType("text");

                            b1.Property<string>("Transcription")
                                .HasColumnType("text");

                            b1.Property<string>("Translation")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.ObjectHistory", "ObjectHistory", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("GeneralHistory")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("ObjectHistoryDetails")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.PlaceOfElaboration", "PlaceOfElaboration", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Canton")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .HasColumnType("text");

                            b1.Property<string>("SpecificPlace")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.ReasonedClassification", "ReasonedClassification", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Classification")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.SignaturesAndMarks", "SignaturesAndMarks", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Author")
                                .HasColumnType("text");

                            b1.Property<string>("CharacterType")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Language")
                                .HasColumnType("text");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Method")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Script")
                                .HasColumnType("text");

                            b1.Property<string>("Transcription")
                                .HasColumnType("text");

                            b1.Property<string>("Translation")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.DescriptionClassification.TechnicalCharacteristics", "TechnicalCharacteristics", b1 =>
                        {
                            b1.Property<Guid>("DescriptionClassificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Characteristics")
                                .HasColumnType("text");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.HasKey("DescriptionClassificationId");

                            b1.ToTable("DescriptionClassifications");

                            b1.WithOwner()
                                .HasForeignKey("DescriptionClassificationId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("Bibliography");

                    b.Navigation("CollectionProvenance");

                    b.Navigation("CulturalContext");

                    b.Navigation("Decoration");

                    b.Navigation("DescriptionDimensions");

                    b.Navigation("Inscriptions");

                    b.Navigation("ObjectHistory");

                    b.Navigation("PlaceOfElaboration");

                    b.Navigation("ReasonedClassification");

                    b.Navigation("SignaturesAndMarks");

                    b.Navigation("TechnicalCharacteristics");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.GraphicDocumentation", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.GraphicDocumentation", "expediente")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Dimensions", "dimensions", b1 =>
                        {
                            b1.Property<Guid>("GraphicDocumentationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision");

                            b1.HasKey("GraphicDocumentationId");

                            b1.ToTable("GraphicDocumentations");

                            b1.WithOwner()
                                .HasForeignKey("GraphicDocumentationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.ImageAuthor", "imageAuthor", b1 =>
                        {
                            b1.Property<Guid>("GraphicDocumentationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IdentityCard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Institution")
                                .HasColumnType("text");

                            b1.Property<string>("InstitutionalId")
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("References")
                                .HasColumnType("text");

                            b1.HasKey("GraphicDocumentationId");

                            b1.ToTable("GraphicDocumentations");

                            b1.WithOwner()
                                .HasForeignKey("GraphicDocumentationId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("dimensions");

                    b.Navigation("imageAuthor");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Identification", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithMany()
                        .HasForeignKey("expediente")
                        .HasPrincipalKey("expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Author", "author", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DeathDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeathPlace")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Material", "material", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Colors")
                                .HasColumnType("text");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("MaterialName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Section", "section", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Courtyard")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayCase")
                                .HasColumnType("text");

                            b1.Property<string>("Easel")
                                .HasColumnType("text");

                            b1.Property<string>("Others")
                                .HasColumnType("text");

                            b1.Property<string>("Panel")
                                .HasColumnType("text");

                            b1.Property<string>("Pillar")
                                .HasColumnType("text");

                            b1.Property<string>("Room")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Storage")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.SpecificName", "specificName", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("GenericName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("RelatedTerms")
                                .HasColumnType("text");

                            b1.Property<string>("SpecificTerms")
                                .HasColumnType("text");

                            b1.Property<string>("UsedBy")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Technique", "techniques", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("TechniqueName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Title", "title", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Translation")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Typology", "typology", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Class")
                                .HasColumnType("text");

                            b1.Property<string>("Order")
                                .HasColumnType("text");

                            b1.Property<string>("Subclass")
                                .HasColumnType("text");

                            b1.Property<string>("Suborder")
                                .HasColumnType("text");

                            b1.Property<string>("Subtype")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("author")
                        .IsRequired();

                    b.Navigation("material")
                        .IsRequired();

                    b.Navigation("section")
                        .IsRequired();

                    b.Navigation("specificName")
                        .IsRequired();

                    b.Navigation("techniques")
                        .IsRequired();

                    b.Navigation("title")
                        .IsRequired();

                    b.Navigation("typology")
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.TemporalMovement", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithMany()
                        .HasForeignKey("Expediente")
                        .HasPrincipalKey("expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Applicant", "Applicant", b1 =>
                        {
                            b1.Property<Guid>("TemporalMovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IdentityCard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("InstitutionalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Observations")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("References")
                                .HasColumnType("text");

                            b1.HasKey("TemporalMovementId");

                            b1.ToTable("TemporalMovements");

                            b1.WithOwner()
                                .HasForeignKey("TemporalMovementId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Departure", "Departure", b1 =>
                        {
                            b1.Property<Guid>("TemporalMovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Company")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Time")
                                .HasColumnType("text");

                            b1.HasKey("TemporalMovementId");

                            b1.ToTable("TemporalMovements");

                            b1.WithOwner()
                                .HasForeignKey("TemporalMovementId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Representative", "Representative", b1 =>
                        {
                            b1.Property<Guid>("TemporalMovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IdentityCard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("InstitutionalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Observations")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("References")
                                .HasColumnType("text");

                            b1.HasKey("TemporalMovementId");

                            b1.ToTable("TemporalMovements");

                            b1.WithOwner()
                                .HasForeignKey("TemporalMovementId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Return", "Return", b1 =>
                        {
                            b1.Property<Guid>("TemporalMovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Company")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("Time")
                                .HasColumnType("text");

                            b1.HasKey("TemporalMovementId");

                            b1.ToTable("TemporalMovements");

                            b1.WithOwner()
                                .HasForeignKey("TemporalMovementId");
                        });

                    b.Navigation("Applicant")
                        .IsRequired();

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("Departure");

                    b.Navigation("Representative");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
